/*
  score.js
  Reads ?scores= from upload page redirect OR fetch JSON from localStorage
*/

// Try reading data saved by upload.js frontend
const data = JSON.parse(localStorage.getItem("resume-result"));

if (!data) {
  document.getElementById("summary").innerText =
    "No backend response found!";
}

// Extract scores
const scores = data?.scores || {};
const overall = scores.overall || 0;
const clarity = scores.clarity || 0;
const relevance = scores.relevance || 0;
const format = scores.format || 0;
const suggestions = scores.suggestions || "No suggestions returned.";

// Update DOM
document.getElementById("percent").innerText = overall + "%";
document.getElementById("clarity").innerText = clarity + "%";
document.getElementById("relevance").innerText = relevance + "%";
document.getElementById("format").innerText = format + "%";
document.getElementById("summary").innerText =
  "These values are generated by backend scoring.";
document.getElementById("suggestions").innerText = suggestions;

// Update circle animation color
document.getElementById("circle").style.background = `
  conic-gradient(#00c853 ${overall * 3.6}deg, #eee 0deg)
`;
